import { Platform, StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#16161E',
  },
  contentWrapper: {
    flex: 1,
    flexDirection: 'row',
  },
  mainLayer: {
    flex: 1,
  },
  drawerShell: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    width: '64%',
    maxWidth: 292,
    minWidth: 236,
    flexDirection: 'row',
    zIndex: 20,
  },
  drawerScrim: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.45)',
    zIndex: 10,
  },
  leftSwipeArea: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    width: 22,
    zIndex: 30,
  },
  serverSidebar: {
    width: 84,
    backgroundColor: '#16161E',
    paddingTop: 25,
    alignItems: 'center',
    shadowColor: '#000000',
    shadowOpacity: 0.45,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 0 },
    elevation: 9,
  },
  homeSection: {
    width: '100%',
    alignItems: 'center',
    marginBottom: 10,
  },
  homeButtonWrapper: {
    width: '100%',
    height: 58,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
  },
  homeSelectionBackground: {
    position: 'absolute',
    left: 13,
    top: 10,
    width: 84,
    height: 38,
    borderTopLeftRadius: 10,
    borderBottomLeftRadius: 10,
    backgroundColor: '#854FBB',
    overflow: 'hidden',
  },
  homeSelectionFade: {
    position: 'absolute',
    left: 14,
    top: 0,
    width: 70,
    height: 38,
    backgroundColor: '#BB9AF7',
    opacity: 0.45,
  },
  homeIconContainer: {
    width: 59,
    height: 59,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: 'rgba(187,154,247,0.2)',
    backgroundColor: '#1F2335',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000000',
    shadowOpacity: 0.5,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 0 },
    elevation: 8,
  },
  homeIcon: {
    width: 40,
    height: 40,
  },
  onlineBlock: {
    alignItems: 'center',
  },
  onlineText: {
    color: '#949BA4',
    fontSize: 14,
    fontWeight: '500',
    marginBottom: 10,
    fontFamily: 'Inter',
  },
  onlineDivider: {
    width: 50,
    height: 1,
    backgroundColor: '#454B53',
  },
  serverList: {
    width: '100%',
    flex: 1,
  },
  serverListContent: {
    alignItems: 'center',
    paddingTop: 20,
    paddingBottom: 20,
  },
  serverButton: {
    width: '100%',
    alignItems: 'center',
    marginBottom: 20,
  },
  serverCircle: {
    width: 50,
    height: 50,
    borderRadius: 50,
    borderWidth: 1,
    borderColor: 'rgba(187,154,247,0.2)',
    backgroundColor: '#1F2335',
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
  },
  serverCircleSelected: {
    borderColor: '#BB9AF7',
  },
  serverCircleOutline: {
    width: 50,
    height: 50,
    borderRadius: 50,
    borderWidth: 1,
    borderColor: 'rgba(187,154,247,0.2)',
    backgroundColor: '#1F2335',
    alignItems: 'center',
    justifyContent: 'center',
  },
  serverImage: {
    width: '100%',
    height: '100%',
    borderRadius: 50,
  },
  serverInitial: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '600',
    fontFamily: 'Inter',
  },
  plusText: {
    color: '#BB9AF7',
    fontSize: 24,
    lineHeight: 24,
  },
  materialIconText: {
    color: '#949BA4',
    fontSize: 24,
    lineHeight: 24,
    fontFamily: Platform.OS === 'web' ? 'Material Symbols Rounded' : undefined,
    fontWeight: Platform.OS === 'web' ? '300' : '600',
  },
  channelSidebar: {
    flex: 1,
    backgroundColor: '#272736',
    borderLeftWidth: 1,
    borderLeftColor: 'rgba(187,154,247,0.2)',
    shadowColor: '#000000',
    shadowOpacity: 0.3,
    shadowRadius: 16,
    shadowOffset: { width: -8, height: 0 },
    elevation: 7,
    overflow: 'hidden',
  },
  headerRow: {
    height: 58,
    backgroundColor: '#16161E',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#BB9AF7',
  },
  guildHeaderTitle: {
    flex: 1,
    color: '#E1E2E8',
    fontSize: 18,
    fontWeight: '700',
    fontFamily: 'Inter',
    paddingHorizontal: 6,
  },
  searchField: {
    flex: 1,
    height: 40,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(187,154,247,0.2)',
    backgroundColor: '#1E1F22',
    justifyContent: 'center',
    paddingHorizontal: 12,
    opacity: 0.9,
  },
  searchText: {
    color: '#949BA4',
    fontSize: 14,
    fontWeight: '500',
    fontFamily: 'Inter',
  },
  headerAddButton: {
    width: 40,
    height: 40,
    marginLeft: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  purpleGlow: {
    height: 12,
    backgroundColor: '#A274F4',
    opacity: 0.12,
  },
  dashedDivider: {
    borderBottomWidth: 1,
    borderColor: '#BB9AF7',
    borderStyle: 'dashed',
  },
  listArea: {
    flex: 1,
  },
  listAreaContent: {
    paddingLeft: 10,
    paddingTop: 20,
    paddingRight: 10,
    paddingBottom: 24,
  },
  friendsRow: {
    height: 40,
    borderRadius: 6,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    marginBottom: 10,
    backgroundColor: 'rgba(255,255,255,0.04)',
  },
  friendsText: {
    color: '#949BA4',
    fontSize: 15,
    marginLeft: 8,
    fontWeight: '500',
    fontFamily: 'Inter',
  },
  dmTitle: {
    color: '#949BA4',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '700',
    marginBottom: 10,
    fontFamily: 'Inter',
  },
  guildInviteButton: {
    height: 36,
    borderRadius: 6,
    backgroundColor: '#454B53',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 14,
  },
  guildInviteText: {
    color: '#E1E2E8',
    fontSize: 14,
    fontWeight: '600',
    fontFamily: 'Inter',
  },
  guildSectionHeader: {
    height: 28,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 6,
    marginBottom: 4,
  },
  guildSectionTitle: {
    color: '#949BA4',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.3,
    fontFamily: 'Inter',
  },
  guildChannelRow: {
    minHeight: 34,
    borderRadius: 6,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    marginBottom: 4,
    gap: 6,
  },
  guildChannelRowSelected: {
    backgroundColor: 'rgba(255,255,255,0.1)',
  },
  guildChannelName: {
    flex: 1,
    color: '#949BA4',
    fontSize: 16,
    fontFamily: 'Inter',
  },
  guildCategoryBlock: {
    marginTop: 4,
    marginBottom: 4,
  },
  guildCategoryHeader: {
    minHeight: 26,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    paddingHorizontal: 4,
  },
  guildCategoryTitle: {
    flex: 1,
    color: '#949BA4',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.3,
    fontFamily: 'Inter',
  },
  guildEmptyText: {
    color: '#7E8492',
    fontSize: 13,
    marginTop: 10,
    fontFamily: 'Inter',
  },
  dmRow: {
    minHeight: 42,
    paddingVertical: 5,
    paddingHorizontal: 5,
    borderRadius: 6,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 5,
  },
  firstDmRow: {
    minHeight: 44,
  },
  dmRowSelected: {
    backgroundColor: 'rgba(255,255,255,0.04)',
  },
  dmAvatarWrapper: {
    width: 32,
    height: 32,
    position: 'relative',
    marginRight: 10,
  },
  dmAvatar: {
    width: 32,
    height: 32,
    borderRadius: 32,
    borderWidth: 1,
    borderColor: 'rgba(187,154,247,0.2)',
  },
  dmAvatarFallback: {
    width: 32,
    height: 32,
    borderRadius: 32,
    borderWidth: 1,
    borderColor: 'rgba(187,154,247,0.2)',
    backgroundColor: '#1F2335',
    alignItems: 'center',
    justifyContent: 'center',
  },
  dmAvatarFallbackText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '600',
  },
  dmStatusShell: {
    position: 'absolute',
    right: -2,
    bottom: -2,
    width: 12,
    height: 12,
    borderRadius: 12,
    backgroundColor: '#272736',
    alignItems: 'center',
    justifyContent: 'center',
  },
  dmStatusDot: {
    width: 8,
    height: 8,
    borderRadius: 8,
  },
  dmTextBlock: {
    flex: 1,
    justifyContent: 'center',
  },
  dmName: {
    color: '#949BA4',
    fontSize: 16,
    lineHeight: 20,
    fontWeight: '400',
    fontFamily: 'Inter',
  },
  dmSubtitle: {
    color: '#50565E',
    fontSize: 12,
    lineHeight: 14,
    marginTop: 1,
    fontFamily: 'Inter',
  },
  dmCard: {
    minHeight: 42,
    paddingVertical: 5,
    paddingHorizontal: 5,
    borderRadius: 6,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 5,
  },
  dmCardSelected: {
    backgroundColor: 'rgba(255,255,255,0.04)',
  },
  dmCardIconWrap: {
    width: 32,
    height: 32,
    position: 'relative',
    marginRight: 10,
  },
  dmCardAvatar: {
    width: 32,
    height: 32,
    borderRadius: 32,
    borderWidth: 1,
    borderColor: 'rgba(187,154,247,0.2)',
  },
  dmCardAvatarFallback: {
    width: 32,
    height: 32,
    borderRadius: 32,
    borderWidth: 1,
    borderColor: 'rgba(187,154,247,0.2)',
    backgroundColor: '#1F2335',
    alignItems: 'center',
    justifyContent: 'center',
  },
  dmCardAvatarFallbackText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '600',
    fontFamily: 'Inter',
  },
  dmCardStatusShell: {
    position: 'absolute',
    right: -2,
    bottom: -2,
    width: 12,
    height: 12,
    borderRadius: 12,
    backgroundColor: '#272736',
    alignItems: 'center',
    justifyContent: 'center',
  },
  dmCardStatusDot: {
    width: 8,
    height: 8,
    borderRadius: 8,
  },
  dmCardTypingDot: {
    backgroundColor: '#BB9AF7',
  },
  dmCardInfo: {
    flex: 1,
    justifyContent: 'center',
  },
  dmCardTitle: {
    color: '#949BA4',
    fontSize: 16,
    lineHeight: 20,
    fontWeight: '400',
    fontFamily: 'Inter',
  },
  dmCardSubtitle: {
    color: '#50565E',
    fontSize: 12,
    lineHeight: 14,
    marginTop: 1,
    fontFamily: 'Inter',
  },
  dmCloseButton: {
    width: 26,
    height: 26,
    alignItems: 'center',
    justifyContent: 'center',
  },
  mainContent: {
    flex: 1,
    backgroundColor: '#1F2335',
    borderLeftWidth: 1,
    borderLeftColor: 'rgba(187,154,247,0.2)',
  },
  mainHeader: {
    height: 58,
    backgroundColor: '#16161E',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(187,154,247,0.2)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
  },
  mainHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  mainHeaderRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  mainHeaderIcon: {
    color: '#949BA4',
    fontSize: 24,
    lineHeight: 24,
    marginRight: 6,
    fontFamily: Platform.OS === 'web' ? 'Material Symbols Rounded' : undefined,
  },
  mainHeaderTitle: {
    color: '#E1E2E8',
    fontSize: 16,
    fontWeight: '600',
    fontFamily: 'Inter',
    flex: 1,
  },
  mainIconButton: {
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 2,
  },
  messagesScroller: {
    flex: 1,
  },
  messagesScrollerContent: {
    paddingHorizontal: 10,
    paddingTop: 12,
    paddingBottom: 16,
  },
  messageRow: {
    flexDirection: 'row',
    marginBottom: 12,
  },
  messageAvatar: {
    width: 32,
    height: 32,
    borderRadius: 32,
    backgroundColor: '#2A2D42',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
    borderWidth: 1,
    borderColor: 'rgba(187,154,247,0.2)',
  },
  messageAvatarText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '700',
    fontFamily: 'Inter',
  },
  messageBody: {
    flex: 1,
  },
  messageHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 2,
  },
  messageAuthor: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
    marginRight: 8,
    fontFamily: 'Inter',
  },
  messageTime: {
    color: '#7E8492',
    fontSize: 11,
    fontFamily: 'Inter',
  },
  messageContent: {
    color: '#C9CDD6',
    fontSize: 14,
    lineHeight: 20,
    fontFamily: 'Inter',
  },
  guildPlaceholder: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  guildPlaceholderTitle: {
    color: '#E1E2E8',
    fontSize: 30,
    fontWeight: '700',
    marginBottom: 10,
    fontFamily: 'Inter',
  },
  guildPlaceholderBody: {
    color: '#949BA4',
    fontSize: 16,
    lineHeight: 22,
    fontFamily: 'Inter',
  },
  chatBar: {
    minHeight: 56,
    backgroundColor: '#1E1F22',
    borderTopWidth: 1,
    borderTopColor: 'rgba(187,154,247,0.2)',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  chatAddButton: {
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 6,
  },
  chatInput: {
    flex: 1,
    height: 38,
    borderRadius: 8,
    backgroundColor: '#272736',
    borderWidth: 1,
    borderColor: 'rgba(187,154,247,0.2)',
    color: '#E1E2E8',
    paddingHorizontal: 10,
    fontSize: 14,
    fontFamily: 'Inter',
  },
  chatActionButton: {
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 6,
  },
  bottomNav: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 80,
    height: Platform.OS === 'ios' ? 70 : 60,
    paddingBottom: Platform.OS === 'ios' ? 10 : 0,
    backgroundColor: '#1E1F22',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    shadowColor: '#000000',
    shadowOpacity: 0.25,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: -4 },
    elevation: 6,
  },
  bottomNavButton: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bottomLogoIcon: {
    width: 34,
    height: 34,
  },
  userAvatarWrap: {
    width: 30,
    height: 30,
    borderRadius: 30,
    position: 'relative',
  },
  userAvatar: {
    width: 30,
    height: 30,
    borderRadius: 30,
  },
  userAvatarFallback: {
    width: 30,
    height: 30,
    borderRadius: 30,
    backgroundColor: '#F0932E',
    alignItems: 'center',
    justifyContent: 'center',
  },
  userAvatarFallbackText: {
    color: '#16161E',
    fontSize: 12,
    fontWeight: '700',
    fontFamily: 'Inter',
  },
  userStatusShell: {
    position: 'absolute',
    width: 10,
    height: 10,
    borderRadius: 10,
    right: -1,
    bottom: -1,
    backgroundColor: '#1E1F22',
    alignItems: 'center',
    justifyContent: 'center',
  },
  userStatusDot: {
    width: 6,
    height: 6,
    borderRadius: 6,
    backgroundColor: '#23A55A',
  },
});
